Sidebar
zuzik772/beta-boulders pull request #1
Opened 2022-12-05 11:50 UTC by zuzik772

includes, basic setup, navigation and sidebar

2022-12-05 19:52 UTC, aszulc97 requested changes

2022-12-05 19:52 UTC, aszulc97 commented on src/App.jsx
> +            <Route path="/stock" element={<Stock />} />
let's rename the stock to the inventory

2022-12-05 19:52 UTC, aszulc97 commented on src/components/Logo.jsx
> +    <li>
does it have to be `<li>`? I'm thinking it might cause problem once I'm gonna put it on the login page. Or not? 

I know that it's because there's `<ul>` in the nav, but can't we just change it all to divs?

2022-12-05 19:52 UTC, aszulc97 commented on src/components/Search.jsx
> +      <span className="font-bold text-md">Search</span>
why isn't it `<input>`?

2022-12-05 19:52 UTC, aszulc97 commented on src/components/Sidebar.jsx
> +  console.log(isPageActive);
remove console.log

2022-12-05 19:52 UTC, aszulc97 commented on src/components/Nav.jsx
> +      <Profile />
what about the dropdown?

2022-12-05 19:52 UTC, aszulc97 commented on src/components/Sidebar.jsx
> +            <Link to="/stock" className={isActive ? "text-accent" : "text-dark"}>
renaming to inventory needed here too

2022-12-05 19:52 UTC, aszulc97 commented on src/img/stock1.svg
> +<?xml version="1.0" encoding="iso-8859-1"?>
there is 3 stock icons now, can you delete the ones that are not needed?

2022-12-06 10:16 UTC, zuzik772 commented on src/App.jsx
> +            <Route path="/stock" element={<Stock />} />
okay, i will

2022-12-06 10:17 UTC, zuzik772 commented on src/components/Logo.jsx
> +    <li>
hmm, semantically should be li i think, but yes i can change it to divs

2022-12-06 10:17 UTC, zuzik772 commented on src/components/Search.jsx
> +      <span className="font-bold text-md">Search</span>
because my brain didnt work

2022-12-06 10:17 UTC, zuzik772 commented on src/components/Search.jsx
> +      <span className="font-bold text-md">Search</span>
i will fix it right away

2022-12-06 10:18 UTC, zuzik772 commented on src/components/Sidebar.jsx
> +  console.log(isPageActive);
ok

2022-12-06 10:18 UTC, zuzik772 commented on src/components/Nav.jsx
> +      <Profile />
i havent done it but i can just create quick component for now

2022-12-06 10:18 UTC, zuzik772 commented on src/components/Sidebar.jsx
> +            <Link to="/stock" className={isActive ? "text-accent" : "text-dark"}>
ok

2022-12-06 11:42 UTC, aszulc97 commented on src/App.jsx
> +            <Route path="/stock" element={<Inventory />} />
`path="/stock"`

2022-12-06 12:13 UTC, zuzik772 commented
I think its ready, I have changed some icons, so they are more elegant, let me know what you think

2022-12-06 12:42 UTC, aszulc97 commented on src/components/Profile.jsx
> +    <li className="bg-fadedAccent w-12 h-12 rounded-full flex items-center justify-center cursor-pointer absolute top-6 right-6">
`<li>` here

2022-12-06 12:44 UTC, aszulc97 commented on src/App.jsx
> +            <Route path="/stock" element={<Inventory />} />
I don't know, maybe my github is bugging, but for me it still shows "stock" in path

2022-12-09 10:37 UTC, aszulc97 approved these changes

2022-12-09 10:37 UTC, merged