Flowbite
zuzik772/beta-boulders pull request #2
Opened 2022-12-09 14:42 UTC by zuzik772

dashboard, posts and flowbite

2022-12-09 19:59 UTC, aszulc97 requested changes

2022-12-09 19:59 UTC, aszulc97 commented on src/components/Schedule.jsx
> +      {/* <div className="grid">
remove commented code

2022-12-09 19:59 UTC, aszulc97 commented on src/components/Tasks.jsx
> +        <TasksListItem title="cleaning coffee machine" desc="see manual" />
I think we shouldn't have `TasksListItem` and `TasksDoneItem` because then what happens if you mark something as done? We cannot turn one component into another.

I think we should have `TaskItem` that has some `isDone` variable (state) and then whenever `isDone` is true then you show the user icon and strikethrough the text. We could actually use `isChecked` that we use for the checkbox instead of this `isDone`.

But ofc you don't have to worry about the working part of the code, so you can just turn `TasksListItem` and `TasksDoneItem` into one component :)

2022-12-09 19:59 UTC, aszulc97 commented on src/components/icons/SeenByPeople.jsx
> +export default function SeenBypeople() {
typo SeenBypeople -> SeenByPeople

2022-12-09 19:59 UTC, aszulc97 commented on src/components/icons/TaskDoneIcon.jsx
> +export default function TaskDoneIcon() {
I guess we don't need this anymore

2022-12-09 19:59 UTC, aszulc97 commented on src/dashboardCardData.json
> +{
is this file used somewhere?

2022-12-09 19:59 UTC, aszulc97 commented on src/components/Tasks.jsx
> +      <ul className="flex flex-col gap-6 bg-light px-2 lg:pl-2 xl:px-6 py-6">
Why to do tasks are in `<ul>` and the done tasks aren't?

2022-12-09 19:59 UTC, aszulc97 commented on src/pages/Dashboard.jsx
> +        <DashboardSubtitle
Could you rename `DashboardSubtitle` to `DashboardCardHeadline` or something like this? Cause it took me a lot of time to understand what this is :D

2022-12-09 19:59 UTC, aszulc97 commented on src/pages/Dashboard.jsx
> +        {/* <div className="flex gap-1 uppercase font-semibold">
remove commented code

2022-12-09 19:59 UTC, aszulc97 commented on src/pages/Dashboard.jsx
> +      {/* <div className="col-span-2 p-6 mb-5 lg:mb-0">
commented code

2022-12-09 19:59 UTC, aszulc97 commented on src/components/MainTitle.jsx
> +      <span className="p-2 sm:p-0">{props.date}</span>
I guess this date is only for the dashboard, right? Then I think it shouldn't be a part of the component.

But maybe I'm going too much into details, so you can keep it here if you want, you decide.

2022-12-09 19:59 UTC, aszulc97 commented on src/pages/Inventory.jsx
> +          <th>Item</th>
Add column for category and also a "order" button.

2022-12-10 08:22 UTC, zuzik772 commented on src/components/Tasks.jsx
> +        <TasksListItem title="cleaning coffee machine" desc="see manual" />
I think you are definitelly right, I made it only because of the styling purposes

2022-12-10 08:24 UTC, zuzik772 commented on src/components/icons/SeenByPeople.jsx
> +export default function SeenBypeople() {
it was a shy boy

2022-12-10 08:25 UTC, zuzik772 commented on src/dashboardCardData.json
> +{
i wanted to use it in the future, for mapping

2022-12-10 08:25 UTC, zuzik772 commented on src/components/icons/TaskDoneIcon.jsx
> +export default function TaskDoneIcon() {
correct

2022-12-10 08:34 UTC, zuzik772 commented on src/pages/Dashboard.jsx
> +        <DashboardSubtitle
hahaha yes of course, sorry

2022-12-10 08:37 UTC, zuzik772 commented on src/components/Tasks.jsx
> +      <ul className="flex flex-col gap-6 bg-light px-2 lg:pl-2 xl:px-6 py-6">
uu good question, i missed it

2022-12-10 11:07 UTC, aszulc97 approved these changes

2022-12-10 11:07 UTC, aszulc97 commented on src/components/FilterButton.jsx
> +    <button className="border-x border-y border-accent px-2 rounded-xl w-28 font-normal">
I can see that you put a `<button>` in here, but actually we need it to be `<input type="radio">`.
You can either change it now or we can change it when we will make it work, no worries.

If you'd like to change it now, here are some inspirations:
[I think I used this one for foofest](https://codepen.io/phusum/pen/VQrQqy) 
[another one](http://jsfiddle.net/YB8UW/8/)

2022-12-10 11:23 UTC, zuzik772 commented on src/components/FilterButton.jsx
> +    <button className="border-x border-y border-accent px-2 rounded-xl w-28 font-normal">
i checked animal base and it was button so i just copy pasted haha

2022-12-10 11:24 UTC, zuzik772 commented on src/components/FilterButton.jsx
> +    <button className="border-x border-y border-accent px-2 rounded-xl w-28 font-normal">
i am gonna change it now

2022-12-10 11:47 UTC, merged